/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.ci.cd;

public class App {
    public String getGreeting() {
        //prueba random
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
