/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.ci.cd;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
    	//test
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void test2() {
    	//test
        assertEquals(true,true);
    }
}
